name: Aikido Release Gated Scan
on:
  push:
    branches:
      - main

jobs:
  aikido-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Workspace Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Aikido CI API Client
        run: npm install --global @aikidosec/ci-api-client

      - name: Run Aikido Scan
        run: |
          aikido-api-client scan-release ${{ github.event.repository.name }} $GITHUB_SHA \
          --apikey ${{ secrets.AIKIDO_CLIENT_API_KEY }} \
          --fail-on-sast-scan \
          --fail-on-iac-scan \
          --fail-on-secrets-scan